### ISSUE TITLE
Please clearify admin UI usage (REACT or jsonConfig)

### ISSUE THREAD

**Issue by mcm1957** [weberk/ioBroker.uvr16xx-blnet#5]
You specify admin UI to be materialize. On the other side you have an empty jsonConfig.json5 file.

New adapters shoul eithe ruse jsonConfig if the admin UI is ruther simple or react if there admin UI must be more complicated. If you want / must use react, jsonConfig files are obsolete. On the other side you asked for help with jsonCOnfig. In this case react should be removed...

**Comment by weberk** [comment]
If I remove the empty jsonConfig file then https://www.iobroker.dev/adapter-check  is complaining. Therefore I created if to be compliant.

**Comment by weberk** [comment]
Hello @mcm1957 , I do not get jsonConfig running.

In package.json I removed the scripts:
    "build:react": "build-adapter react",
    "watch:react": "build-adapter react --watch",
In io-package.json I switched to:
        "adminUI": {
            "config": "json"
        },
I deleted index_m.html and custom_m.html.
Then added a file admin/jsonConfig.json with my three properties:
`{
    "i18n": true,
    "type": "tabs",
    "tabsStyle": {
        "width": "calc(100% - 100px)"
    },
    "items": {
        "_options": {
            "type": "panel",
            "label": "Adapter Settings",
            "items": {
                "ip_address": {
                    "type": "text",
                    "label": "IP Address",
                    "default": "192.168.2.177",
                    "tooltip": "Enter the IP address of the device",
                    "xs": 6,
                    "sm": 6,
                    "md": 6,
                    "lg": 6,
                    "xl": 6
                },
                "port": {
                    "type": "number",
                    "label": "Port",
                    "default": 65534,
                    "tooltip": "Enter the port number",
                    "xs": 6,
                    "sm": 6,
                    "md": 6,
                    "lg": 6,
                    "xl": 6
                },
                "poll_interval": {
                    "type": "number",
                    "label": "Poll Interval (sec)",
                    "default": 30,
                    "tooltip": "Enter the polling interval in seconds",
                    "xs": 12,
                    "sm": 12,
                    "md": 6,
                    "lg": 6,
                    "xl": 6
                }
            }
        }
    }
}
`
Now if I open the adapter settings on the screen an error is raised claiming "Cannot GET /index_m.html".

Any idea what is missing?

**Comment by mcm1957** [comment]
check adminUi property at io-package.json.

I can take a look later
 I m on mobile only

**Comment by weberk** [comment]
Got JSON-Config working by deleting 
- index_m.html
- style.css
